# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.
#

IOP_BIN  = hddload.irx
IOP_OBJS = hddload.o imports.o
IOP_CFLAGS += -Os -mgpopt -G8192

include $(PS2SDK)/Defs.make
include Rules.bin.make
include Rules.make
